config/routes.rb
Weowe::Application.routes.draw do
  devise_for :users

  resources :demos
  resources :dealers
  resources :weowe_forms
  resources :users

  root 'static_pages#landing_page'

  match '/dashboard', to: 'weowe_forms#dashboard', via: 'get'

  match '/approve_form', to: 'weowe_forms#approve_form', via: 'post'
  match '/complete_form', to: 'weowe_forms#complete_form', via: 'post'

  match '/pending', to: 'weowe_forms#pending',    via: 'get'
  match '/completed', to: 'weowe_forms#completed',    via: 'get'

  match '/metrics', to: 'weowe_forms#metrics', via: 'get'

  match '/admin', to: 'dealers#admin',    via: 'get'

  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/tos', to: 'static_pages#tos', via: 'get'

  match '/staff', to: 'static_pages#staff',    via: 'get'
  match '/overall', to: 'static_pages#overall',    via: 'get'

  match '/landing_page', to: 'static_pages#landing_page',    via: 'get'
end

app/models/demo.rb
class Demo < ActiveRecord::Base
end

app/controllers/demos_controller.rb
class DemosController < ApplicationController
  before_action :set_demo, only: [:show, :edit, :update, :destroy]

  def index
    @demos = Demo.all
  end

  def show
  end

  def new
    @demo = Demo.new
  end

  def edit
  end

  def create
    @demo = Demo.new(demo_params)

    respond_to do |format|
      if @demo.save
        format.html { redirect_to landing_page_path, notice: 'Thank you, we will be in contact soon.' }
        format.json { render action: 'show', status: :created, location: @demo }
      else
        format.html { render action: 'new' }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @demo.update(demo_params)
        format.html { redirect_to @demo, notice: 'Demo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @demo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @demo.destroy
    respond_to do |format|
      format.html { redirect_to demos_url }
      format.json { head :no_content }
    end
  end

  private

  def set_demo
    @demo = Demo.find(params[:id])
  end

  def demo_params
    params.require(:demo).permit(:first_name, :last_name, :phone_number, :email, :dealership)
  end
end

app/views/demos/_form.html.erb
<%= form_for(@demo) do |f| %>
  <% if @demo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@demo.errors.count, "error") %> prohibited this demo from being saved:</h2>

      <ul>
      <% @demo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :dealership %><br>
    <%= f.text_field :dealership %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/demos/edit.html.erb
<h1>Editing demo</h1>

<%= render 'form' %>

<%= link_to 'Show', @demo %> |
<%= link_to 'Back', demos_path %>

app/views/demos/index.html.erb
<h1>Listing demos</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone number</th>
      <th>Email</th>
      <th>Dealership</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @demos.each do |demo| %>
      <tr>
        <td><%= demo.first_name %></td>
        <td><%= demo.last_name %></td>
        <td><%= demo.phone_number %></td>
        <td><%= demo.email %></td>
        <td><%= demo.dealership %></td>
        <td><%= link_to 'Show', demo %></td>
        <td><%= link_to 'Edit', edit_demo_path(demo) %></td>
        <td><%= link_to 'Destroy', demo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Demo', new_demo_path %>

app/views/demos/new.html.erb
<h1>New demo</h1>

<%= render 'form' %>

<%= link_to 'Back', demos_path %>

app/views/demos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @demo.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @demo.last_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @demo.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @demo.email %>
</p>

<p>
  <strong>Dealership:</strong>
  <%= @demo.dealership %>
</p>

<%= link_to 'Edit', edit_demo_path(@demo) %> |
<%= link_to 'Back', demos_path %>