config/routes.rb
Weowe::Application.routes.draw do
  devise_for :users

  resources :demos
  resources :dealers
  resources :weowe_forms
  resources :users

  root 'static_pages#landing_page'

  match '/dashboard', to: 'weowe_forms#dashboard', via: 'get'

  match '/approve_form', to: 'weowe_forms#approve_form', via: 'post'
  match '/complete_form', to: 'weowe_forms#complete_form', via: 'post'

  match '/pending', to: 'weowe_forms#pending',    via: 'get'
  match '/completed', to: 'weowe_forms#completed',    via: 'get'

  match '/metrics', to: 'weowe_forms#metrics', via: 'get'

  match '/admin', to: 'dealers#admin',    via: 'get'

  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/tos', to: 'static_pages#tos', via: 'get'

  match '/staff', to: 'static_pages#staff',    via: 'get'
  match '/overall', to: 'static_pages#overall',    via: 'get'

  match '/landing_page', to: 'static_pages#landing_page',    via: 'get'
end

app/models/dealer.rb
class Dealer < ActiveRecord::Base
  has_many :users
  has_many :weowe_forms

  validates_presence_of :name
  validates_presence_of :address_1
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :zip
  validates_inclusion_of :time_zone,
                         in: ActiveSupport::TimeZone.zones_map(&:name)

  ATTACHED_PATH = ':rails_root/public/system/:attachment/:id/:style/:filename'

  has_attached_file :logo,
                    path: ATTACHED_PATH,
                    url: '/system/:attachment/:id/:style/:filename'

  validates_attachment :logo, content_type: { content_type: ['image/jpg', 'image/jpeg', 'image/png'] }
end

app/controllers/dealers_controller.rb
class DealersController < ApplicationController
  before_action :set_dealer, only: [:show, :edit, :update, :destroy]

  def index
    redirect_to root_path
  end

  def show
  end

  def admin
    if stale?(@dealer)
      @dealer = Dealer.find(current_user.dealer_id)
    end
  end

  def new
    if current_user
      @dealer = Dealer.new
    else
      redirect_to root_path
    end
  end

  def edit
  end

  def create
    @dealer = Dealer.new(dealer_params)
    message = 'Dealer was successfully created.'
    handle_action(@dealer, message, :new, &:save)
  end

  def update
    message = 'Dealer was successfully updated.'

    handle_dealer_action(@dealer, message, admin_path) do |resource|
      resource.update(dealer_params)
    end
  end

  def destroy
    @dealer.destroy
    respond_to do |format|
      format.html { redirect_to dealers_url }
      format.json { head :no_content }
    end
  end

  private

  include ApplicationHelper
  include DealersHelper

  def set_dealer
    @dealer = Dealer.find(params[:id])
  end
end

app/helpers/dealers_helper.rb
module DealersHelper
  DEALER_PARAMS = [:name,
                   :address_1,
                   :address_2,
                   :city,
                   :state,
                   :zip,
                   :phone_number,
                   :time_zone,
                   :logo,
                   :email_domain
                  ]

  def dealer_params
    params.require(:dealer).permit(DEALER_PARAMS)
  end
end

app/views/dealers/_form.html.erb
<div class='userform well'>
  <%= bootstrap_form_for(@dealer) do |f| %>

    <h1 class='hidden-xs'><%= legend %></h1>
    <center><h3 class='visible-xs'><%= legend %></h3></center>

    <%= f.text_field :name, hide_label: :true,
                     placeholder: 'Dealership Name *' %>
    <%= f.text_field :address_1, hide_label: :true,
                     placeholder: 'Address 1 *' %>
    <%= f.text_field :address_2, hide_label: :true,
                     placeholder: 'Address 2' %>
    <%= f.text_field :city, hide_label: :true,
                     placeholder: 'City *' %>
    <%= f.text_field :state, hide_label: :true,
                     placeholder: 'State *' %>
    <%= f.text_field :zip, hide_label: :true,
                     placeholder: 'Zip Code *' %>
    <%= f.text_field :phone_number, hide_label: :true,
                     placeholder: 'Phone Number' %>
    <%= f.text_field :email_domain, hide_label: :true,
                     placeholder: 'Email Domain',
                      placeholder: 'Email domain: e.g., DealerEmailDomain.com' %>
    <%= f.file_field :logo %>

    <button type='submit' class='btn btn-block btn-primary'>
      <i class='fa fa-refresh'></i> Update Dealership Information
    </button>
  <% end %>
</div>
</div>

app/views/dealers/admin.html.erb
<% provide(:title, 'Preferences') %>
<div ng-app='weowepro'>
  <!-- <div ng-controller='UsersCtrl'> -->
    <div ng-init='data.dealer = <%= @dealer.to_json %>'></div>

    <h1>Preferences</h1>

    <center>
      <div class='table-width-desktop'>
         <div class='panel panel-default'>
           <div class='panel-heading'>
             <h3 class='panel-title'>Dealership</h3>
           </div>
           <div class='panel-body'>
            <table class='table'>
              <tbody>
                 <tr>
                 <th>Logo</th>
                   <td><%= image_tag @dealer.logo.url, width: '200px' %>
                   </td>
                 </tr>
                <tr>
                  <th>Name</th>
                  <td>{{::data.dealer.name}}</td>
                </tr>
                <tr>
                  <th>Address 1</th>
                  <td>{{::data.dealer.address_1}}</td>
                </tr>
                <tr>
                  <th>Address 2</th>
                  <td>{{::data.dealer.address_2}}</td>
                </tr>
                <tr>
                  <th>City</th>
                  <td>{{::data.dealer.city}}</td>
                </tr>
                <tr>
                  <th>State</th>
                  <td>{{::data.dealer.state}}</td>
                </tr>
                <tr>
                  <th>Zip</th>
                  <td>{{::data.dealer.zip}}</td>
                </tr>
                <tr>
                  <th>Phone Number</th>
                  <td>
                    <a href='tel:{{data.dealer.phone_number}}'>
                      {{data.dealer.phone_number}}
                    </a>
                  </td>
                </tr>
                <tr>
                  <th>Domain</th>
                  <td>{{::dealer.email_domain}}</td>
                </tr>
                <tr>
                  <td> <%= link_to ' Edit', edit_dealer_path(current_user.dealer_id),
                    class: 'fa fa-pencil fa-lg' %>
                  </td>
                  <td></td>
                </tr>
              </tbody>
            </table>
           </div>
         </div>

          <br>
          <div class='panel panel-default'>
            <div class='panel-heading'>
              <h3 class='panel-title'>Export</h3>
            </div>
            <div class='panel-body'>
              <div class='visible-xs'>
                <%= link_to 'Sales Staff Contact Information', users_path(format: 'csv'),
                    class: 'btn btn-primary btn-sm btn-block' %>
                <%= link_to 'Sales Forms', pending_path(format: 'csv'),
                    class: 'btn btn-danger btn-sm btn-block' %>
                <%= link_to 'Service Forms', weowe_forms_path(format: 'csv'),
                    class: 'btn btn-warning btn-sm btn-block' %>
                <%= link_to 'Completed Forms', completed_path(format: 'csv'),
                    class: 'btn btn-success btn-sm btn-block' %>
              </div>
              <div class='hidden-xs'>
                <%= link_to 'Sales Staff Contact Information', users_path(format: 'csv'),
                    class: 'btn btn-primary btn-sm', style: 'width: 200px;'%>
                <%= link_to 'Sales Forms', pending_path(format: 'csv'),
                    class: 'btn btn-danger btn-sm', style: 'width: 200px;' %>
                <%= link_to 'Service Forms', weowe_forms_path(format: 'csv'),
                    class: 'btn btn-warning btn-sm', style: 'width: 200px;' %>
                <%= link_to 'Completed Forms', completed_path(format: 'csv'),
                    class: 'btn btn-success btn-sm', style: 'width: 200px;' %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </center>
  </div>
</div>

app/views/dealers/edit.html.erb
<% provide(:title, 'Edit Dealership') %>
<%= render 'form', :legend => 'Edit Dealership', :dealer => @dealer %>

app/views/dealers/show.html.erb
<% provide(:title, "#{@dealer.name}") %>

<h1>My Dealership Information</h1>

<div id='userformbutton'>
<%=link_to 'Edit Information', edit_dealer_path(@dealer),
    class: 'btn btn-primary btn-sm'%>
</div>

<br><br>

<div class='table-responsive'>
  <table class='table table-bordered table-condensed' >
    <tr>
    <th style='width:25%'>Name</th>
      <td><%= @dealer.name %></td>
    </tr>
    <th>Logo</th>
      <td><%= image_tag @dealer.logo.url, height: '100' %></td>
    </tr>
    <tr>
    <th>Address 1</th>
      <td><%= @dealer.address_1 %></td>
    </tr>
    <tr>
    <th>Address 2</th>
      <td><%= @dealer.address_2 %></td>
    </tr>
    <tr>
    <th>City</th>
      <td><%= @dealer.city %></td>
    </tr>
    <tr>
    <th>State</th>
      <td><%= @dealer.state %></td>
    </tr>
    <tr>
    <th>Zip Code</th>
      <td><%= @dealer.zip %></td>
    </tr>
    <tr>
    <th>Phone Number</th>
      <td><%= @dealer.phone_number %></td>
    </tr>
      <th>Time Zone</th>
        <td><%= @dealer.time_zone %></td>
    </tr>
  </table>
</div>