config/routes.rb
Weowe::Application.routes.draw do
  devise_for :users

  resources :demos
  resources :dealers
  resources :weowe_forms
  resources :users

  root 'static_pages#landing_page'

  match '/dashboard', to: 'weowe_forms#dashboard', via: 'get'

  match '/approve_form', to: 'weowe_forms#approve_form', via: 'post'
  match '/complete_form', to: 'weowe_forms#complete_form', via: 'post'

  match '/pending', to: 'weowe_forms#pending',    via: 'get'
  match '/completed', to: 'weowe_forms#completed',    via: 'get'

  match '/metrics', to: 'weowe_forms#metrics', via: 'get'

  match '/admin', to: 'dealers#admin',    via: 'get'

  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/tos', to: 'static_pages#tos', via: 'get'

  match '/staff', to: 'static_pages#staff',    via: 'get'
  match '/overall', to: 'static_pages#overall',    via: 'get'

  match '/landing_page', to: 'static_pages#landing_page',    via: 'get'
end

app/views/layouts/_footer.html.erb
<footer class='footer hidden-print'>
  <center>
  <p style='color: #C0C0C0'>&#169; 2014 Allen Industries LLC</p>
  <%= debug(params) if Rails.env.development? %>
  </center>
</footer>

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-52447209-2', 'auto');
  ga('send', 'pageview');
</script>

app/views/layouts/_header.html.erb
<div id='top_nav'>
  <center>
    <div id='nav_logo'>
      <%= link_to 'WeOwePro', dashboard_path, id: 'logo' %>
    </div>
  </center>
</div>

<div class='navbar navbar-inverse navbar-static-top'>
  <div class='container'>
    <button class='navbar-toggle' data-toggle='collapse'
    data-target='.navHeaderCollapse'>
      <span class='icon-bar'></span>
      <span class='icon-bar'></span>
      <span class='icon-bar'></span>
    </button>
    <div class='collapse navbar-collapse navHeaderCollapse'>
      <ul class='nav navbar-nav navbar-right' >
        <% if user_signed_in? %>
          <% if current_user.admin == true %>
            <li class='<%= active_link_to_class('#',
                active: [['users'], ['index']]) %>'>
              <a href='/users'><span class='fa fa-users fa-lg'> Staff</span></a>
            </li>
          <% end %>

          <% if current_user.admin == true %>
            <li class="<%= active_link_to_class('#',
                active: [['static_pages'], ['overall', 'staff']]) %> dropdown">
              <a class='dropdown-toggle' data-toggle = 'dropdown'>
                <span class='fa fa-bar-chart fa-lg'> Statistics</span>
                <b class = 'caret'></b>
                </a>
              <ul class = 'dropdown-menu'>
                <li><a href='/metrics'>Sales Staff</span></a></li>
                  <li><a href='/overall'>Dealership</span></a></li>
              </ul>
            </li>

          <% end %>

          <li class="<%= active_link_to_class('#',
              active: [['weowe_forms'], ['index', 'show', 'new', 'edit', 'pending', 'completed']]) %> dropdown">
            <a href = '#' class = 'dropdown-toggle' data-toggle = 'dropdown'>
              <span class='fa fa-list-alt fa-lg'> Forms</span>
              <span style='background-color:#009587;' class='badge'>
                <%= WeoweForm.where(dealer_id: current_user.dealer_id, pending: false, completed: false).count %> In Service
              </span>
              <b class = 'caret'></b>
              </a>
            <ul class = 'dropdown-menu'>
              <li><%= link_to 'New Form', new_weowe_form_path %></li>
              <li><%= link_to 'Sales', pending_path %></li>
              <li><%= link_to 'Service', weowe_forms_path %></li>
              <li><%= link_to 'Completed', completed_path %></li>
            </ul>
          </li>

          <li class="<%= active_link_to_class('#',
              active: [['users', 'dealers'], ['show', 'edit', 'admin']]) %> dropdown">
            <a href = '#' class = 'dropdown-toggle' data-toggle = 'dropdown'>
              <span class='fa fa-cog fa-lg'> Account</span>
              <b class = 'caret'></b></a>
            <ul class = 'dropdown-menu'>
              <li><%= link_to 'My Profile', current_user %></li>
              <% if current_user.admin == true %>
                <li><%= link_to 'Preferences', admin_path %></li>
              <% end %>
              <li class='divider'></li>
              <li>
                <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_landing_page_footer.html.erb
<footer class='footer' id='footer_landing_page_fix'>
  <center>

  <p style='color: #C0C0C0'>
    <a style='color: #C0C0C0' href = '/privacy'>
      Privacy
    </a> |
    <a style='color: #C0C0C0' href = '/tos'>
      Terms of Service
    </a>
  </p>

  <p style='color: #C0C0C0'>&#169; 2014 Allen Industries LLC</p>
  </center>
</footer>

<style>
 #footer_landing_page_fix {
  padding-top: 0px;
  margin-top: 0px;
 }
</style>

app/views/layouts/_landing_page_header.html.erb
<nav class='navbar-static-top' id='special_nav_top'>
  <div class='container'>
    <div class='pull-right' id='sign_in_button'>
      <%= link_to 'Sign In', new_user_session_path,
        class: 'btn btn-success btn-xs', role: 'button' %>
    </div>
  </div>
</nav>
<div class = 'navbar navbar-default navbar-static-top' id='special_nav_bottom'>
  <div class = 'container'>
    <% if @skip_footer == false %>
    <button class = 'navbar-toggle' data-toggle = 'collapse'
    data-target = '.navHeaderCollapse'>
      <span class = 'icon-bar'></span>
      <span class = 'icon-bar'></span>
      <span class = 'icon-bar'></span>
    </button>
     <% end %>
    <div id='logo_landing_page'> WeOwePro</div>
    <div id='logo_landing_page_subheader'
         class='hidden-xs'> ELIMINATE PAPER FORMS WITH EASE </div>
      <% if @skip_footer == false %>
        <div class = 'collapse navbar-collapse navHeaderCollapse'>

          <ul class = 'nav navbar-nav navbar-right' >
            <li class='nav_element_fix'>
              <%= link_to 'Features', '#features' %>
            </li>
            <li class='nav_element_fix'>
              <%= link_to 'Demo', '#demo' %>
            </li>
            <li class='nav_element_fix'>
              <%= link_to 'Get Started Today', '#demo' %>
            </li>
          </ul>

        </div>
        <div class='pull-right hidden-xs' id='cta_button_1'>
          <%= link_to 'Get Started Today', '#demo',
            class: 'btn btn-primary btn-sm', role: 'button' %>
        </div>
    <% else %>
      <div class='pull-right' id='cta_button_2'>
        <%= link_to 'Back To Home', root_path,
          class: 'btn btn-primary btn-sm', role: 'button' %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <meta name='viewport' content='width=device-width, initial-scale=1.0 user-scalable=no'>
    <%= stylesheet_link_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css', 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class='hidden-print'>
      <%= render 'layouts/header' %>
    </div>
    <div class='container'>
      <%= custom_bootstrap_flash %>
      <%= yield %>
      <%= render 'layouts/footer' unless @skip_footer %>
    </div>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html id='devise_html'>
  <head>
    <title><%= full_title(yield(:title))%></title>
    <meta name='viewport' content='width=device-width, initial-scale=1.0 user-scalable=no'>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css', 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body id='devise_body'>
    <div class='container'>
      <% if !current_user %>
        <br><br>
      <% end %>
      <%= custom_bootstrap_flash %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/landing_page.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WeOwePro</title>
    <meta name='description'
          content='Web app for managing We Owe Forms. Mobile/Tablet support.
                   Robust Analytics.'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0 user-scalable=no'>
    <%= stylesheet_link_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css', 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/google_analytics' %>
  </head>
  <body>
    <%= custom_bootstrap_flash %>
    <%= render 'layouts/landing_page_header' %>
    <div>
      <%= yield %>
      <%= render 'layouts/landing_page_footer' %>
    </div>
  </body>
</html>